### ISSUE TITLE
[Bug]: segfault in bctoolbox

### ISSUE THREAD

**Issue by netmax79** [BelledonneCommunications/bctoolbox#15]
### Context

I use this project in a custom app running on Linux with the sip.linphone.org service for my company. I want to do a simple call between an Android phone and a Linux client. There is an error with a method of this project and I'm sure that I followed the documentation and double checked before posting.

### General information

- Device:
- OS: openSUSE Tumbleweed 20220305
- Version of the App: 5.1
- Version of the SDK:

libbctoolbox1-5.1.0-1.1.x86_64
liblinphone++10-5.0.67-1.2.x86_64
liblinphone10-5.0.67-1.2.x86_64
liblinphone-data-5.0.67-1.2.noarch
liblinphone-lang-5.0.67-1.2.noarch
libsrtp2-linphone1-2.2.0~git.20210916-1.3.x86_64
linphone-4.3.2-2.2.x86_64
linphone-cli-5.0.67-1.2.x86_64

Today i updated my local tumbleweed installation and it pulled new version of libbctoolbox1|5.1.0-1.1|x86_64|
The version which was installed before was |libbctoolbox1|5.0.67-1.1|x86_64

Now when i start linphone it crashes with segfault after a second, i ran it through gdb and collected following output:

carsten@trabant:~> gdb /usr/bin/linphone
GNU gdb (GDB; openSUSE Tumbleweed) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/linphone...
Reading symbols from /home/carsten/.cache/debuginfod_client/1ee61b46b7b2124e08ccea5e888c0993f7f9ba45/debuginfo...
(gdb) run
Starting program: /usr/bin/linphone 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffedb93640 (LWP 14542)]
[New Thread 0x7fffe7fff640 (LWP 14564)]
[New Thread 0x7fffe5c45640 (LWP 14630)]
[New Thread 0x7fffe5444640 (LWP 14631)]
[New Thread 0x7fffe4c43640 (LWP 14632)]
[New Thread 0x7fffd9fbe640 (LWP 14633)]
[New Thread 0x7fffd97bd640 (LWP 14634)]
[New Thread 0x7fffd8fbc640 (LWP 14635)]
[New Thread 0x7fffc3fff640 (LWP 14636)]
[New Thread 0x7fffc37fe640 (LWP 14637)]
[New Thread 0x7fffc2ffd640 (LWP 14638)]
[New Thread 0x7fffc27fc640 (LWP 14639)]
[New Thread 0x7fffc1ffb640 (LWP 14640)]
[New Thread 0x7fffc17fa640 (LWP 14641)]
[New Thread 0x7fffc0ff9640 (LWP 14642)]
[New Thread 0x7fff9ffff640 (LWP 14643)]
[New Thread 0x7fff97fff640 (LWP 14644)]
[New Thread 0x7fff9f7fe640 (LWP 14645)]
[New Thread 0x7fff9effd640 (LWP 14652)]
[New Thread 0x7fff9e7fc640 (LWP 14665)]
[New Thread 0x7fff9dffb640 (LWP 14666)]
[New Thread 0x7fff9d7fa640 (LWP 14667)]
[New Thread 0x7fff9cff9640 (LWP 14668)]
[New Thread 0x7fff977fe640 (LWP 14669)]
[New Thread 0x7fff96ffd640 (LWP 14670)]
[New Thread 0x7fff967fc640 (LWP 14671)]
[New Thread 0x7fff95ffb640 (LWP 14672)]
[12:24:05:973][0x555555d1b230][Info]"Starting Linphone (bin: linphone)"
[12:24:05:973][0x555555d1b230][Info]"Use locale: de_DE"
[12:24:06:049][0x555555d1b230][Info]Available fonts :  ("Adobe Courier", "Adobe Helvetica", "Adobe New Century Schoolbook [PfEd]", "Adobe New Century Schoolbook [Adobe]", "Adobe Symbol", "Adobe Times [Adobe]", "Adobe Times [PfEd]", "Adobe Utopia [Adobe]", "Adobe Utopia [PfEd]", "Arabic Newspaper [PfEd]", "Arabic Newspaper [Arabic]", "B&H Lucida [PfEd]", "B&H Lucida [B&H]", "B&H LucidaBright [B&H]", "B&H LucidaBright [PfEd]", "B&H LucidaTypewriter [B&H]", "B&H LucidaTypewriter [PfEd]", "Bitstream Charter [Bitstream]", "Bitstream Charter [PfEd]", "Bitstream Terminal", "Cantarell", "Carlito", "Century Schoolbook L [PfEd]", "Century Schoolbook L [urw]", "Classic Console", "Courier [PfEd]", "Courier [ibm]", "Courier 10 Pitch [bitstream]", "Courier 10 Pitch [PfEd]", "Courier-converted", "Cursor", "cursor.pcf", "Daewoo Gothic Wide", "Daewoo Mincho Wide", "DEC Terminal", "deccurs.pcf", "decsess.pcf", "DejaVu Math TeX Gyre", "DejaVu Sans", "DejaVu Sans Condensed", "DejaVu Sans Mono", "DejaVu Serif", "DejaVu Serif Condensed", "Dingbats [PfEd]", "Dingbats [urw]", "Droid Arabic Kufi", "Droid Arabic Naskh", "Droid Naskh Shift Alt", "Droid Sans", "Droid Sans Armenian", "Droid Sans Devanagari", "Droid Sans Ethiopic", "Droid Sans Fallback", "Droid Sans Georgian", "Droid Sans Hebrew", "Droid Sans Japanese", "Droid Sans Mono", "Droid Sans Tamil", "Droid Sans Thai", "Droid Serif", "East Syriac Adiabene", "East Syriac Ctesiphon", "Efont Biwidth", "Efont Fixed", "Efont Fixed Wide", "Estrangelo Antioch", "Estrangelo Edessa", "Estrangelo Midyat", "Estrangelo Nisibin", "Estrangelo Nisibin Outline", "Estrangelo Quenneshrin", "Estrangelo Talada", "Estrangelo TurAbdin", "ETL Fixed", "gallant12x22", "Goha-Tibeb Zemen", "Hack", "Helvetica-converted", "ISAS Fangsong ti Wide", "ISAS Song ti Wide", "JIS Fixed Wide", "Latin Modern Mono", "Latin Modern Mono Caps", "Latin Modern Mono Light", "Latin Modern Mono Light Cond", "Latin Modern Mono Prop", "Latin Modern Mono Prop Light", "Latin Modern Mono Slanted", "Latin Modern Roman", "Latin Modern Roman Caps", "Latin Modern Roman Demi", "Latin Modern Roman Dunhill", "Latin Modern Roman Slanted", "Latin Modern Roman Unslanted", "Latin Modern Sans", "Latin Modern Sans Demi Cond", "Latin Modern Sans Quotation", "Liberation Mono", "Liberation Sans", "Liberation Serif", "LM Mono 10", "LM Mono 12", "LM Mono 8", "LM Mono 9", "LM Mono Caps 10", "LM Mono Light 10", "LM Mono Light Cond 10", "LM Mono Prop 10", "LM Mono Prop Light 10", "LM Mono Slanted 10", "LM Roman 10", "LM Roman 12", "LM Roman 17", "LM Roman 5", "LM Roman 6", "LM Roman 7", "LM Roman 8", "LM Roman 9", "LM Roman Caps 10", "LM Roman Demi 10", "LM Roman Dunhill 10", "LM Roman Slanted 10", "LM Roman Slanted 12", "LM Roman Slanted 17", "LM Roman Slanted 8", "LM Roman Slanted 9", "LM Roman Unslanted 10", "LM Sans 10", "LM Sans 12", "LM Sans 17", "LM Sans 8", "LM Sans 9", "LM Sans Demi Cond 10", "LM Sans Quot 8", "Luxi Mono [B&H ]", "Luxi Mono [b&h]", "Luxi Sans [b&h]", "Luxi Sans [B&H ]", "Luxi Serif [b&h]", "Luxi Serif [B&H ]", "micro.pcf", "Misc Fixed", "Misc Fixed Wide", "Monospace", "MUTT ClearlyU Alternate Glyphs Wide [PfEd]", "MUTT ClearlyU Alternate Glyphs Wide [MUTT]", "MUTT ClearlyU Arabic Extra", "MUTT ClearlyU PUA [MUTT]", "MUTT ClearlyU PUA [PfEd]", "MUTT ClearlyU Wide [MUTT]", "MUTT ClearlyU Wide [PfEd]", "Nimbus Mono L [urw]", "Nimbus Mono L [PfEd]", "Nimbus Roman No9 L [PfEd]", "Nimbus Roman No9 L [urw]", "Nimbus Roman No9 L [omega]", "Nimbus Sans L [PfEd]", "Nimbus Sans L [urw]", "Noto Color Emoji", "Noto Sans", "Noto Sans Blk", "Noto Sans Cond", "Noto Sans Cond Blk", "Noto Sans Cond ExtBd", "Noto Sans Cond ExtLt", "Noto Sans Cond Light", "Noto Sans Cond Med", "Noto Sans Cond SemBd", "Noto Sans Cond Thin", "Noto Sans ExtBd", "Noto Sans ExtCond", "Noto Sans ExtCond Blk", "Noto Sans ExtCond ExtBd", "Noto Sans ExtCond ExtLt", "Noto Sans ExtCond Light", "Noto Sans ExtCond Med", "Noto Sans ExtCond SemBd", "Noto Sans ExtCond Thin", "Noto Sans ExtLt", "Noto Sans Light", "Noto Sans Med", "Noto Sans SemBd", "Noto Sans SemCond", "Noto Sans SemCond Blk", "Noto Sans SemCond ExtBd", "Noto Sans SemCond ExtLt", "Noto Sans SemCond Light", "Noto Sans SemCond Med", "Noto Sans SemCond SemBd", "Noto Sans SemCond Thin", "Noto Sans Thin", "Noto Sans UI", "OCR A Std", "Open Sans", "Open Sans Condensed", "Open Sans Condensed Light", "Open Sans ExtraBold", "Open Sans Light", "Open Sans SemiBold", "Poppins", "Poppins Black", "Poppins ExtraBold", "Poppins ExtraLight", "Poppins Light", "Poppins Medium", "Poppins SemiBold", "Poppins Thin", "Roboto", "Roboto Black", "Roboto Condensed", "Roboto Condensed Light", "Roboto Condensed Medium", "Roboto Light", "Roboto Medium", "Roboto Thin", "Sans Serif", "Schumacher Clean [Schumacher]", "Schumacher Clean [PfEd]", "Schumacher Clean Wide [PfEd]", "Schumacher Clean Wide [Schumacher]", "Serif", "Serto Batnan", "Serto Jerusalem", "Serto Jerusalem Outline", "Serto Kharput", "Serto Malankara", "Serto Mardin", "Serto Urhoy", "Sony Fixed", "Source Code Pro", "Source Code Pro Black", "Source Code Pro ExtraLight", "Source Code Pro Light", "Source Code Pro Medium", "Source Code Pro Semibold", "Source Sans 3", "Source Sans 3 Black", "Source Sans 3 ExtraLight", "Source Sans 3 Light", "Source Sans 3 Semibold", "Source Sans Pro", "Source Sans Pro Black", "Source Sans Pro ExtraLight", "Source Sans Pro Light", "Source Sans Pro Semibold", "Source Serif Pro", "Source Serif Pro Black", "Source Serif Pro ExtraLight", "Source Serif Pro Light", "Source Serif Pro Semibold", "Special Elite", "Standard Symbols L [urw]", "Standard Symbols L [PfEd]", "STIXGeneral", "URW Bookman L [PfEd]", "URW Bookman L [urw]", "URW Chancery L [PfEd]", "URW Chancery L [urw]", "URW Gothic L [PfEd]", "URW Gothic L [urw]", "URW Palladio L [PfEd]", "URW Palladio L [urw]", "Utopia [PfEd]", "Utopia [adobe]")
[12:24:06:049][0x555555d1b230][Info]"Running app..."
[New Thread 0x7fff957fa640 (LWP 14673)]
[12:24:06:087][0x555555d1b230][Info]"Activated selectors:" ("custom", "de_DE", "unix", "linux", "opensuse-tumbleweed")
[12:24:06:088][0x555555d1b230][Info]"Registering types..."
[12:24:06:088][0x555555d1b230][Info]"Registering shared types..."
[12:24:06:088][0x555555d1b230][Info]"Registering tool types..."
[12:24:06:088][0x555555d1b230][Info]"Registering shared tool types..."
[12:24:07:193][0x555555d1b230][Info]"Loading main view..."
[12:24:07:818][0x555555d1b230][Info]"Launch async core creation."
[New Thread 0x7fff5ffff640 (LWP 14676)]
[New Thread 0x7fff5f7fe640 (LWP 14677)]
[Thread 0x7fff5f7fe640 (LWP 14677) exited]
[New Thread 0x7fff5f7fe640 (LWP 14678)]
[Thread 0x7fff5f7fe640 (LWP 14678) exited]
[12:24:08:419][0x555555d1b230][Info]Core is starting  "Starting up"
[12:24:08:469][0x555555d1b230][Info]Core is running  "On"
[12:24:08:469][0x555555d1b230][Info]"Set `Friends` path: `/home/carsten/.local/share/linphone/friends.db`"
[12:24:08:474][0x555555d1b230][Info]"Set `CallLogs` path: `/home/carsten/.local/share/linphone/call-history.db`"
[12:24:08:482][0x555555d1b230][Info]Using ZrtpSecrets path :  "/home/carsten/.local/share/linphone/zidcache"
[12:24:08:482][0x555555d1b230][Info]Using UserCertificate path :  "/home/carsten/.local/share/linphone/usr-crt/"
[12:24:08:482][0x555555d1b230][Info]Using RootCa path :  "/usr/share/linphone/rootca.pem"
[12:24:08:482][0x555555d1b230][Info]"Start iterate"
[12:24:08:502][0x555555d1b230][Info]Sip addresses model from Chats : 19 ms.
[12:24:08:509][0x555555d1b230][Info]Sip addresses model from Calls : 6 ms.
[12:24:08:509][0x555555d1b230][Info]Sip addresses model from Refs : 0 ms.
[12:24:08:509][0x555555d1b230][Info]Sip addresses model from Contacts : 0 ms.
[12:24:08:509][0x555555d1b230][Info]Sip addresses model initialized in: 25 ms.
[12:24:08:535][0x555555d1b230][Info]"Notify event count: 0."
[12:24:08:535][0x555555d1b230][Info]"CoreManager initialized"
[12:24:08:593][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineSearchPlaceholderText, disambiguation=)"
[12:24:08:622][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterEphemerals, disambiguation=)"
[12:24:08:625][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterSecureChatGroups, disambiguation=)"
[12:24:08:625][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterChatGroups, disambiguation=)"
[12:24:08:626][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterSecureRooms, disambiguation=)"
[12:24:08:626][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterSimpleRooms, disambiguation=)"
[12:24:08:627][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilter, disambiguation=)"
[12:24:08:627][0x555555d1b230][Debug]"Unable to find a translation. (context=Timeline, label=timelineFilterAll, disambiguation=)"
[12:24:08:644][0x555555d1b230][Debug]"Unable to find a translation. (context=MainWindowMenuBar, label=checkForUpdates, disambiguation=)"
[12:24:08:651][0x555555d1b230][Debug]"Unable to find a translation. (context=MainWindow, label=newChatRoom, disambiguation=)"
[12:24:08:677][0x555555d1b230][Debug]"Unable to find a translation. (context=MainWindow, label=openHome, disambiguation=)"
[12:24:08:679][0x555555d1b230][Debug]"Unable to find a translation. (context=MainWindow, label=hideTimeline, disambiguation=)"
[New Thread 0x7fff5f7fe640 (LWP 14679)]
[12:24:08:918][0x555555d1b230][Info]"Open Linphone app."
[12:24:08:918][0x555555d1b230][Info]"Creating subwindow: `qrc:/ui/views/App/Calls/CallsWindow.qml`."
[12:24:09:914][0x555555d1b230][Info]"Subwindow status: `1`."
[12:24:09:960][0x555555d1b230][Info]"Creating subwindow: `qrc:/ui/views/App/Settings/SettingsWindow.qml`."
[12:24:10:220][0x555555d1b230][Info]"Subwindow status: `1`."
[12:24:10:541][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsAdvanced, label=noPlugin, disambiguation=)"
[12:24:10:541][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsAdvanced, label=noPlugin, disambiguation=)"
[12:24:10:614][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=checkForUpdateLabel, disambiguation=)"
[12:24:10:614][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=mipmapTooltip1, disambiguation=)"
[12:24:10:614][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=mipmapTooltip2, disambiguation=)"
[12:24:10:615][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=mipmapLabel, disambiguation=)"
[12:24:10:641][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=fontsTitle, disambiguation=)"
[12:24:10:641][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=fontsPopupTitle, disambiguation=)"
[12:24:10:647][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsUi, label=fontsTextChange, disambiguation=)"
[12:24:10:653][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelApply, disambiguation=)"
[12:24:10:653][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelAddServer, disambiguation=)"
[12:24:10:654][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=serverDualMode, disambiguation=)"
[12:24:10:657][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=serverMode, disambiguation=)"
[12:24:10:657][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=proxyHttpApply, disambiguation=)"
[12:24:10:657][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=proxyHttpPassword, disambiguation=)"
[12:24:10:658][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=proxyHttpUsername, disambiguation=)"
[12:24:10:658][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=proxyHttpPort, disambiguation=)"
[12:24:10:661][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=proxyHttpHost, disambiguation=)"
[12:24:10:661][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=setHTTPProxy, disambiguation=)"
[12:24:10:668][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelSIP, disambiguation=)"
[12:24:10:668][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelUsername, disambiguation=)"
[12:24:10:669][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelDomain, disambiguation=)"
[12:24:10:669][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsTunnel, label=tunnelStatus, disambiguation=)"
[12:24:10:686][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsCallsChat, label=hideEmptyChatRoomsLabel, disambiguation=)"
[12:24:10:694][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsCallsChat, label=waitRegistrationForCallLabel, disambiguation=)"
[12:24:10:707][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsAudio, label=echoCancellationCalibrationLabel, disambiguation=)"
[12:24:10:749][0x555555d1b230][Debug]"Unable to find a translation. (context=SettingsWindow, label=tunnelTab, disambiguation=)"
[12:24:14:677][0x555555d1b230][Info]"Notify event count: 0."

Thread 1 "linphone" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff50b81e3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff5068306 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5051813 in __GI_abort () at abort.c:79
#4  0x00007ffff7678596 in bctbx_logv (domain=<optimized out>, level=BCTBX_LOG_FATAL, fmt=0x7ffff4e83b0c "Bad cast to %s at %s:%i", args=0x7fffffffd270) at /usr/src/debug/bctoolbox-5.1.0-1.1.x86_64/src/logging/logging.c:570
#5  0x00007ffff4cc891b in bctbx_fatal (fmt=<optimized out>) at /usr/include/bctoolbox/logging.h:245
#6  0x00007ffff4cc921a in belle_sip_object_cast (fileno=274, file=0x7ffff7d9b8c8 "/home/abuild/rpmbuild/BUILD/liblinphone-5.0.67/coreapi/bellesip_sal/sal_impl.c", castname=0x7ffff7d72413 "belle_sip_body_handler_t", id=111, obj=<optimized out>)
    at /usr/src/debug/belle-sip-5.1.0-1.1.x86_64/src/belle_sip_object.c:480
#7  belle_sip_object_cast (obj=<optimized out>, id=111, castname=0x7ffff7d72413 "belle_sip_body_handler_t", file=0x7ffff7d9b8c8 "/home/abuild/rpmbuild/BUILD/liblinphone-5.0.67/coreapi/bellesip_sal/sal_impl.c", fileno=274)
    at /usr/src/debug/belle-sip-5.1.0-1.1.x86_64/src/belle_sip_object.c:477
#8  0x00007ffff7aea137 in sal_body_handler_from_content (content=0x55555a650ee0, parseMultipart=<optimized out>) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/src/c-wrapper/api/c-content.cpp:479
#9  0x00007ffff7cfba22 in _linphone_event_send_publish (notify_err=1 '\001', body=0x55555a650ee0, lev=0x55555a885d20) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/coreapi/event.c:389
#10 linphone_event_send_publish (lev=0x55555a885d20, body=0x55555a650ee0) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/coreapi/event.c:414
#11 0x00007ffff7ab28a5 in LinphonePrivate::Account::sendPublish (this=0x5555568304a0, presence=0x55555682e920) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/src/account/account.cpp:990
#12 0x00007ffff7ab6966 in LinphonePrivate::Account::update (this=0x5555568304a0) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/src/account/account.cpp:918
#13 LinphonePrivate::Account::update (this=0x5555568304a0) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/src/account/account.cpp:910
#14 0x00007ffff76763de in bctbx_list_for_each (list=0x555556878590, func=0x7ffff7d32940 <linphone_proxy_config_update(LinphoneProxyConfig*)>) at /usr/src/debug/bctoolbox-5.1.0-1.1.x86_64/src/containers/list.c:172
#15 0x00007ffff7d171f6 in proxy_update (lc=0x555556663e70) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/coreapi/linphonecore.c:3897
#16 linphone_core_iterate (lc=0x555556663e70) at /usr/src/debug/linphone-5.0.67-1.2.x86_64/coreapi/linphonecore.c:4043
#17 0x0000555555711b76 in CoreManager::iterate() ()
#18 0x00007ffff586d503 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffd6e0, r=0x5555565fb210, this=0x5555569c5860) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#19 doActivate<false> (sender=0x555555dd05e0, signal_index=3, argv=0x7fffffffd6e0) at kernel/qobject.cpp:3886
#20 0x00007ffff58669cf in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7ffff5b0cc00 <QTimer::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd6e0) at kernel/qobject.cpp:3946
#21 0x00007ffff58713ba in QTimer::timeout (this=<optimized out>, _t1=...) at .moc/moc_qtimer.cpp:205
#22 0x00007ffff58633cf in QObject::event (this=0x555555dd05e0, e=0x7fffffffd860) at kernel/qobject.cpp:1336
#23 0x00007ffff6640a7f in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555dd05e0, e=0x7fffffffd860) at kernel/qapplication.cpp:3632
#24 0x00007ffff5836e3a in QCoreApplication::notifyInternal2 (receiver=0x555555dd05e0, event=0x7fffffffd860) at kernel/qcoreapplication.cpp:1064
#25 0x00007ffff588d72b in QTimerInfoList::activateTimers (this=0x555555e07910) at kernel/qtimerinfo_unix.cpp:643
#26 0x00007ffff588dffc in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:183
#27 idleTimerSourceDispatch (source=source@entry=0x555555e08cc0) at kernel/qeventdispatcher_glib.cpp:230
#28 0x00007ffff208be22 in g_main_dispatch (context=0x7fffe8005010) at ../glib/gmain.c:3381
#29 g_main_context_dispatch (context=0x7fffe8005010) at ../glib/gmain.c:4099
#30 0x00007ffff208c1b8 in g_main_context_iterate (context=context@entry=0x7fffe8005010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4175
#31 0x00007ffff208c26f in g_main_context_iteration (context=0x7fffe8005010, may_block=1) at ../glib/gmain.c:4240
#32 0x00007ffff588e384 in QEventDispatcherGlib::processEvents (this=0x555555e13210, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#33 0x00007ffff583583b in QEventLoop::exec (this=this@entry=0x7fffffffdaa0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#34 0x00007ffff583db10 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#35 0x00005555556399fd in main ()
(gdb) quit

I'm not 100% sure, but #4 looks like the error line where it starts to crash. Any help would be great!

### Expected behaviour

linphone should start up normally

### To Reproduce

1. Install opensuse tubleweed from 20220305 (this is rolling release)
2. start linphone

**Comment by netmax79** [comment]
The crash seems to be resolved by an update of liblinphone today:

> 2022-03-14 06:23:30|install|liblinphone-data|5.0.70-1.1|noarch||download.opensuse.org-oss|91114885cce73fc1beaf4c8321e67ff9d108c00c1063475ce3846678fe95805a|
2022-03-14 06:23:54|install|liblinphone10|5.0.70-1.1|x86_64||download.opensuse.org-oss|045fa473543608f832451f8d007fb9c18b8d90792f80de449627cbf668d5eff5|
2022-03-14 06:24:09|install|liblinphone-lang|5.0.70-1.1|noarch||download.opensuse.org-oss|28eab8b84775e98497708ebce4f391ff5a8a681e371df07ab6d03c667045892c|
2022-03-14 06:24:32|install|linphone-cli|5.0.70-1.1|x86_64||download.opensuse.org-oss|52e55b0dc241470ee1449e3d0cbaf29a2f8255222a90499bd431136134df00be|
2022-03-14 06:24:32|install|liblinphone++10|5.0.70-1.1|x86_64||download.opensuse.org-oss|22612b35c3e7684d16402cefb71b1b60994e860aed6d21f9616865d410d9fc44|
